Login screen
ImmortalIdiot/RUTLead-Android pull request #22
Opened 2024-03-02 23:43 UTC by NN171

Added the values of Inter font, sign in button. The login screen was rewrote, also added a logo app.

2024-03-03 02:33 UTC, ImmortalIdiot commented
Result:
![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/127626768/6611faec-e762-492b-92b1-be36e07b58fd)
Please, change the colors.

2024-03-03 02:37 UTC, ImmortalIdiot commented
I specifically added the "Dimensions.kt" file so that we wouldn't write values in dp in the files, but use variables from the Dimensions.kt. Replace all dp values with variables from the file. Add other dimensions if necessary.

2024-03-04 21:24 UTC, NN171 commented
Changed it, also changed the pallete of DarkColorScheme and LightColorScheme. Added new dimensions values, replaced the dp values to dimensions values. Added a custom cursor. Fixed the button shape and its border

2024-03-04 21:27 UTC, NN171 commented
> Result: ![image](https://private-user-images.githubusercontent.com/127626768/309519748-6611faec-e762-492b-92b1-be36e07b58fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1ODc5MDgsIm5iZiI6MTcwOTU4NzYwOCwicGF0aCI6Ii8xMjc2MjY3NjgvMzA5NTE5NzQ4LTY2MTFmYWVjLWU3NjItNDkyYi05MmIxLWJlMzZlMDdiNThmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNFQyMTI2NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YzM0ZjI0ODg1YWU0NmE0N2JkMDYzMDM5NDI0NGRjMTM2M2ZjNzQ5ZjBiMWU0ZTU3YTZkYmM4MGExZmQzNmJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.XSbk3hinBqMigZGhTwEW2MsSos1wJuTLekuqWcK6-GE) Please, change the colors.

It was changed

2024-03-04 21:28 UTC, NN171 commented
> I specifically added the "Dimensions.kt" file so that we wouldn't write values in dp in the files, but use variables from the Dimensions.kt. Replace all dp values with variables from the file. Add other dimensions if necessary.

Replaced all dp values.

2024-03-04 21:29 UTC, NN171 commented
Dp values was replaced by the dimensions values

2024-03-04 22:31 UTC, NN171 commented on app/src/main/res/drawable/design_ic_visibility.xml
Was done

2024-03-04 22:32 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +            .border(BorderStroke(3.dp, Color.Transparent),
Method BorderStroke() was removed

2024-03-04 22:33 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/auth/Login.kt
> +                    .background(LightBlue),
Replaced by dimensions values

2024-03-04 23:45 UTC, ImmortalIdiot requested changes

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                    Row(modifier = Modifier
All parameters should be written on new lines.

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    CompositionLocalProvider(LocalTextSelectionColors provides customCursorHandleColor) {
What does this line do?

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/AccountMissing.kt
> +}
Missing an empty line in the end of the file

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/BoxLabel.kt
> +}
Missed an empty line in the end of the file

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +            .height(50.dp)
Recommendation: replace the fixed size (in dp) with a size that depends on the parent container

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +            .width(150.dp)
Recommendation: replace the fixed size (in dp) with a size that depends on the parent container

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +        )) {
Move ") {" to the next line

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +        painterResource(id = R.drawable.password_visibility_off)
Missed an empty line after this line

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                    type,
What is this variable? Specifiy the parameters explicitly.
Example:
My function looks like this:
```Kotlin
fun doWork(
    firstAction: String = "",
    timeForFirstAction: Time = Time.ZERO,
    secondAction: String = "",
    timeForSecondAction: Time = Time.ZERO
) {
    // function body
}
```
When using a function with multiple arguments, you should specify the parameters explicitly.
I want to use my fun doWork() and specify only one parameter firstAction. I should explicitly write it to improve readability:
```Kotlin
val plans = Actions (firstAction = "Coding")
```

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                    style = if (!isFocused || !isFieldEmpty) TextStyle(
Replace the TextStyle container with the usual variable boldInter12 or mediumInter12

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                    else TextStyle(
Replace the TextStyle container with the usual variable boldInter14 or mediumInter14

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            else PasswordVisualTransformation(),
Add tabs to improve readability

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                }) {
Move ") {" to the next line

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            keyboardOptions = KeyboardOptions(
You have only one action with modifier, so you should write on one line.
Example:
```Kotlin
param = function(anotherParam)
```

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    val dimensions = LocalDimensions.current
Missed an empty line after this line

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +                    type,
What it this variable? I have already written about this in the PasswordField.kt

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +                    style = if (!isFocused || !isFieldEmpty) TextStyle(
Replace the TextStyle container with the usual variable boldInter12 or mediumInter12

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +                    else TextStyle(
Replace the TextStyle container with the usual variable boldInter14 or mediumInter14

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +            shape = RoundedCornerShape(15.dp),
Replace dp value from Dimensions.kt (add dimension if necessary)

2024-03-04 23:45 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            shape = RoundedCornerShape(15.dp)
Replace dp value from Dimensions.kt (add dimension if necessary)

2024-03-06 23:09 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    val textLength = 6
Changed to 8 digits

2024-03-06 23:09 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    TextField(
Empty line was added

2024-03-06 23:10 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +                        if (it.text.length <= textLength) text = it
Fixed

2024-03-06 23:11 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +        label = { Text(type,
Reformed

2024-03-06 23:14 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +            style = if (!isFocused) TextStyle(
There's only one method, so I can use if-else without curly brackets

2024-03-06 23:15 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +            ) },
Reformed

2024-03-06 23:16 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +            style = if (!isFocused) TextStyle(
The TextStyle was replaced by the font type

2024-03-06 23:17 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/SignUpRedirect.kt
> +}
The method was deleted

2024-03-06 23:19 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                BorderStroke(width = 3.dp, color = Color.Transparent),
BorderStroke() was deleted, width and color are now using as parameters

2024-03-06 23:20 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            style = if (!isFocused) TextStyle(
The boldInter10 was replaced by mediumInter10

2024-03-06 23:21 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +        ) },
Code has been reformatted

2024-03-06 23:32 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +}
The empty line has been added

2024-03-09 09:52 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +        else PasswordVisualTransformation(),
Has been reformed

2024-03-09 09:58 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/AccountMissing.kt
Has been changed

2024-03-09 09:59 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/AccountMissing.kt
I did it for better code readability

2024-03-09 10:00 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/BoxLabel.kt
Has been transferred

2024-03-09 10:01 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/BoxLabel.kt
Для лучшей читаемости

2024-03-09 10:45 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/SignUpRedirect.kt
So, if this file need to be transferred to the navigation package, the button must be transferred to this package too

2024-03-09 10:45 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/SignUpRedirect.kt
I transferred this file to the components

2024-03-09 10:46 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +}
Has been added

2024-03-09 10:46 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +                BorderStroke(2.dp, Color.White),
It has been replaced

2024-03-09 10:47 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +            Text(text = "Войти",
It was changed

2024-03-09 10:48 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/auth/Login.kt
> +}
Has been added

2024-03-09 10:49 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/auth/Login.kt
> +        Column(horizontalAlignment = Alignment.CenterHorizontally,
Has been changed

2024-03-09 10:53 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                        BorderStroke(2.dp, MaterialTheme.colorScheme.outline),
Has been replaced

2024-03-09 10:54 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/ui/theme/Theme.kt
> +
Has been removed

2024-03-09 10:54 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/ui/theme/Theme.kt
> +
Has been removed

2024-03-09 10:59 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/ui/theme/Color.kt
> +val DarkWhite = Color(0xFFC7D2E5)
Has been changed to lower case

2024-03-09 11:01 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/ui/theme/Color.kt
Has been done

2024-03-09 11:01 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +    val dimensions = LocalDimensions.current
Has been added

2024-03-09 11:02 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +        Column(horizontalAlignment = Alignment.CenterHorizontally,
Has been reformatted

2024-03-09 11:05 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                        BorderStroke(dimensions.borderXSWidth, MaterialTheme.colorScheme.outline),
Has been replaced

2024-03-09 11:08 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                        .fillMaxWidth(0.85f)
Has been changed

2024-03-09 11:08 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                        .fillMaxWidth(),
Has been changed

2024-03-09 11:09 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +}
Was added

2024-03-09 11:09 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/ui/theme/Color.kt
> +}
Was added

2024-03-09 11:09 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                        horizontalArrangement = Arrangement.Center) {
Has been reformatted

2024-03-09 11:30 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                    else R.drawable.ic_app_light_logo
Was added

2024-03-09 11:30 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                    Row(modifier = Modifier
Has been done

2024-03-09 11:33 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    CompositionLocalProvider(LocalTextSelectionColors provides customCursorHandleColor) {
This line permits to change the handle of cursor color
![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/61082311/e976563e-17f4-42d9-8caa-db3a4589aae9) ![image](https://github.com/ImmortalIdiot/RUTLead-project-activity/assets/61082311/53f5e012-dc25-46bc-a23a-3f4d12391502)

2024-03-09 11:34 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/AccountMissing.kt
> +}
Was added

2024-03-09 11:34 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/BoxLabel.kt
> +}
Was added

2024-03-09 11:42 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +            .height(50.dp)
Has been changed

2024-03-09 11:43 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/SignInButton.kt
> +            .width(150.dp)
Has been changed

2024-03-09 11:45 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +        painterResource(id = R.drawable.password_visibility_off)
The empty line after variable declaration has been added

2024-03-09 12:20 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                    type,
The param has been added

2024-03-09 12:20 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                    style = if (!isFocused || !isFieldEmpty) TextStyle(
Has been changed

2024-03-09 12:20 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                    else TextStyle(
Has been changed

2024-03-09 12:21 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            else PasswordVisualTransformation(),
Tabs has been added

2024-03-09 12:23 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +                }) {
Has been reformatted

2024-03-09 12:24 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            keyboardOptions = KeyboardOptions(
Has been changed

2024-03-09 12:24 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    val dimensions = LocalDimensions.current
An empty line has been added

2024-03-09 12:25 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +                    type,
The param was added

2024-03-09 12:26 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +                    style = if (!isFocused || !isFieldEmpty) TextStyle(
The method TextStyle has been replaced by the values

2024-03-09 12:26 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +                    else TextStyle(
The method TextStyle has been replaced by the values

2024-03-09 12:32 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +            shape = RoundedCornerShape(15.dp),
Has been replaced

2024-03-09 12:32 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            shape = RoundedCornerShape(15.dp)
Has been replaced

2024-03-10 13:52 UTC, ImmortalIdiot requested changes
You did a very cool job. I even have a lot to learn. But there are a couple of nuances that I wrote in this review.

2024-03-10 13:52 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/components/login/BoxLabel.kt
Delete unused imports

2024-03-10 13:52 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/components/login/SignUpRedirect.kt
Delete unused imports

2024-03-10 13:52 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
Why is the signleLine parameter specified in the StudentIDField, but not in the PasswordField? Explain your decision to me

2024-03-10 21:50 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
SingleLine parameter was set as "true" in both files early.

2024-03-10 21:52 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/components/login/BoxLabel.kt
Has been removed

2024-03-10 21:52 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/components/login/SignUpRedirect.kt
Has been removed

2024-03-11 07:39 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/MainActivity.kt
> -}
Add new line

2024-03-11 07:41 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/login/SignInButton.kt
> +        modifier = Modifier
```suggestion
fun SignInButton(
    onButtonClick: () -> Unit,
    modifier: Modifier = Modifier
) {
    Button(
        onClick = onButtonClick,
        modifier = modifier
```

2024-03-11 07:43 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/login/SignInButton.kt
> +        modifier = Modifier
Сейчас вы не можете вызвать внутреннюю функцию onClick в Button из вне, с помощью callback onButtonClick, который вы будете передавать в вызываемую функцию, вы сможете :)

Насчёт modifier в параметрах функции SignInButton: благодарю этой передачи, вы сможете в любой момент изменить параметры этой кнопки, её ширину, высоту и т.д. Это считается хорошей практикой, когда функция является универсальной и ее можно изменить в любой момент

2024-03-11 07:46 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/login/SignInButton.kt
> +                text = "Войти",
Тоже самое, добавьте в параметры функции SignInButton какой-нибудь buttonText, таким образом можно будет менять его в момент вызова где угодно, также можно изменить название функции SignInButton на какую-нибудь PrimaryButton, т.к теперь эта функция более универсальна, и вы можете ее кастомизировать где угодно

2024-03-11 07:48 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/components/login/SignUpRedirect.kt
> +            .clickable { /*TODO*/ },
```suggestion
            .clickable { onTextClick() },
```

2024-03-11 07:48 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/components/login/SignUpRedirect.kt
> +        modifier = Modifier
```suggestion
        modifier = modifier
```

2024-03-11 07:49 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    }
```suggestion
    var password by rememberSaveable { mutableStateOf("") }
    var passwordVisible by remember { mutableStateOf(false) }
    var isFocused by remember { mutableStateOf(false) }
    val isFieldEmpty by remember { derivedStateOf { password.isEmpty() } }
```

2024-03-11 07:52 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    }
Нету единого стиля: by remember {} где то на одной строке, где то на двух
+ лучше разделять переменные, которые делают разные задачи: 
dimensons для отступов, что она делает среди remember

2024-03-11 07:52 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    val customCursorHandleColor = TextSelectionColors(
```suggestion
fun PasswordField(
    type: String
    modifier: Modifier = Modifier
) {
    val customCursorHandleColor = TextSelectionColors(
```

2024-03-11 07:53 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            modifier = Modifier
```suggestion
            modifier = modifier
```

2024-03-11 07:55 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    var password by rememberSaveable { mutableStateOf("") }
Не стоит использовать remember для всего, здесь, например, у вас изменяется текст и вы это запоминаете, но ведь у вас это запоминание происходит во viewModel в функции changeLogin & changePassword. Так есть ли смысл запоминать это и там, и тут, не вызовет ли это ошибок?

2024-03-11 07:57 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +            singleLine = true,
А если вам нужно будет где нибудь использовать этот текст, где одной линии будет недостаточно? Не лучше ли сделать это изменяемым параметром?

2024-03-11 07:58 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    var text by remember { mutableStateOf("") }
Тоже самое, что и в PasswordTextField, есть ли смысл запоминать ввод здесь, если он запоминается во viewModel?

2024-03-11 08:00 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/ui/theme/Theme.kt
> +
Extra empty line

2024-03-11 08:00 UTC, ImmortalIdiot requested changes
Actually, Nikita suggested me to make the universal field and just pass the necessary parameters (StudentIDField and Password field replace with a universal field, and when we use this composable function, we will pass the necessary parameters. The same can do with the button.

2024-03-11 08:01 UTC, LittlePony00 commented on app/src/main/res/values/strings.xml
>  </resources>
Добавьте пустую строку

2024-03-11 08:04 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/buttons/login/SignInButton.kt
> +        modifier = Modifier
Thank you for advice

2024-03-11 08:07 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    }
Ok, thank you

2024-03-11 08:08 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    var password by rememberSaveable { mutableStateOf("") }
There is no viewMovel for LoginScreen yet

2024-03-11 08:14 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    var password by rememberSaveable { mutableStateOf("") }
Это не значит, что нужно делать неправильно, а вдруг вы забудете?)

Если хочется проверить функционал, то есть @Preview

2024-03-11 16:56 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/MainActivity.kt
> -}
Already existing

2024-03-11 16:57 UTC, NN171 commented on app/src/main/java/com/immortalidiot/rutlead/ui/theme/Theme.kt
> +
Has been removed

2024-03-11 17:35 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    val icon = if (passwordVisible) painterResource(id = R.drawable.password_visibility_on)
К сожалению, painterResource не использует remember, что делает вашу функцию restartable, из-за этого при каждом изменение чего-либо в этой функции или на экране, где вы ее будете вызывать, эта иконка будет рекомпозироваться. Альтернативой является ImageVector.vectorResource

Также можно почитать статью на эту тему: https://engineering.teknasyon.com/reduce-recomposition-for-images-icons-in-jetpack-compose-8d2dd3bfa933

2024-03-11 17:36 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +                painter = painterResource(
Тоже самое, не следует использовать painterResource, лучше заменить его на ImageVector.vectorResource
https://engineering.teknasyon.com/reduce-recomposition-for-images-icons-in-jetpack-compose-8d2dd3bfa933

2024-03-11 18:03 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +    val textLength = 8
Может лучше вынести в параметр функции? Чтобы сделать эту функцию универсальной и заменить прежнее ее имя на PrimaryTextField, например

2024-03-11 18:03 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/StudentIdField.kt
> +            singleLine = true,
Может лучше не всегда передавать true, а вынести в параметры функции и заменить ее имя на более универсальное?

2024-03-14 19:41 UTC, ImmortalIdiot commented
I refactored screen, added basic field and button, added view model and custom auth exception functions. Remains to make a snackbar and send the error text to it, add a transition to the sign up screen, open a dialog to reset the password and add sending a request to the server for user authorization.

2024-03-14 20:00 UTC, ImmortalIdiot reviewed
I refactored screen, added the basic field and the basic button, added the view model and the custom auth exception functions. Remains to make a snackbar and send the error text to it, add a transition to the sign up screen, open a dialog to reset the password and add sending a request to the server for user authorization.

2024-03-14 20:07 UTC, ImmortalIdiot reviewed
Irrelevant data

2024-03-14 20:10 UTC, ImmortalIdiot reviewed
I don't know why github is requesting my review again...

2024-03-14 20:14 UTC, ImmortalIdiot reviewed
All outdated changed mark as resolved

2024-03-14 20:20 UTC, ImmortalIdiot reviewed
I refactored screen, added the basic field and the basic button, added the view model and the custom auth exception functions. Remains to make a snackbar and send the error text to it (I will add this in this pr), add a transition to the sign up screen, open a dialog to reset the password and add sending a request to the server for user authorization.

2024-03-14 20:27 UTC, ImmortalIdiot approved these changes

2024-03-14 20:28 UTC, ImmortalIdiot commented
I figured out why github displays me as requesting changes. Instead of clicking on "Approve", I clicked on "Comment". I'm dumb.

2024-03-18 23:10 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/buttons/login/PrimaryButton.kt
> +    onButtonClick: () -> Unit,
```suggestion
    onButtonClick: () -> Unit
```

2024-03-18 23:11 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    var isPasswordVisible by remember { mutableStateOf(true) }
во viewmodel вынести

2024-03-18 23:12 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/providers/LocalSnackbarHostState.kt
> +}
```suggestion
}

```

2024-03-18 23:13 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +            LoginScreenViewModel.State.ValidationError)?.studentIDError.toString()
```suggestion
    val studentIDErrorMessage = (state as? LoginScreenViewModel.State.ValidationError)?.studentIDError.toString()
```

2024-03-18 23:13 UTC, LittlePony00 commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +            LoginScreenViewModel.State.ValidationError)?.passwordError.toString()
```suggestion
    val passwordErrorMessage = (state as? LoginScreenViewModel.State.ValidationError)?.passwordError.toString()
```

2024-03-18 23:15 UTC, LittlePony00 commented on app/src/main/res/values/strings.xml
>  </resources>
```suggestion
</resources>

```

2024-03-18 23:23 UTC, LittlePony00 approved these changes

2024-03-18 23:23 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +            LoginScreenViewModel.State.ValidationError)?.studentIDError.toString()
Reformat code doesn't update tabs

2024-03-18 23:23 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/screens/LoginScreen.kt
> +            LoginScreenViewModel.State.ValidationError)?.passwordError.toString()
The same story

2024-03-18 23:25 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    var isPasswordVisible by remember { mutableStateOf(true) }
К полю разве нужна вью модель?

2024-03-18 23:50 UTC, ImmortalIdiot approved these changes

2024-03-18 23:51 UTC, ImmortalIdiot commented on app/src/main/res/values/strings.xml
>  </resources>
Has been added, thx

2024-03-18 23:51 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/providers/LocalSnackbarHostState.kt
> +}
Has been added, thx

2024-03-18 23:51 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/fields/PasswordField.kt
> +    var isPasswordVisible by remember { mutableStateOf(true) }
Has been done, thank you so much

2024-03-18 23:51 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/buttons/login/PrimaryButton.kt
> +    onButtonClick: () -> Unit,
Comma has been removed

2024-03-18 23:52 UTC, ImmortalIdiot commented on app/src/main/java/com/immortalidiot/rutlead/MainActivity.kt
> +                else ThemeColors.Light
Has been reformatted, thx

2024-03-18 23:56 UTC, LittlePony00 approved these changes

2024-03-19 01:07 UTC, merged